### ISSUE TITLE
ERROR: One or more files did not pass the validity check!

### ISSUE THREAD

**Issue by SvenMeyer** [ungoogled-software/ungoogled-chromium-archlinux#279]
Just wanted to do a fresh install on a new freshly install of Manjaro Cinnamon 24.0.5 and got this ...

```
...<snip>...
Installing base-devel (1-3)...
Running post-transaction hooks...
Arming ConditionNeedsUpdate...
Updating the info directory file...

Building ungoogled-chromium-bin...
==> Making package: ungoogled-chromium-bin 127.0.6533.119-1 (Mon 19 Aug 2024 03:48:24 UTC)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading ungoogled-chromium-127.0.6533.119-1-x86_64.pkg.tar.zst...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  1  104M    1 1729k    0     0   790k      0  0:02:15  0:00:02  0:02:13 5178k
  7  104M    7 8273k    0     0  2594k      0  0:00:41  0:00:03  0:00:38 6197k
 13  104M   13 13.8M    0     0  3395k      0  0:00:31  0:00:04  0:00:27 6094k
 19  104M   19 20.0M    0     0  3920k      0  0:00:27  0:00:05  0:00:22 6078k
 25  104M   25 26.1M    0     0  4329k      0  0:00:24  0:00:06  0:00:18 6181k
 30  104M   30 32.0M    0     0  4567k      0  0:00:23  0:00:07  0:00:16 6220k
 36  104M   36 38.4M    0     0  4808k      0  0:00:22  0:00:08  0:00:14 6220k
 42  104M   42 44.3M    0     0  4940k      0  0:00:21  0:00:09  0:00:12 6234k
 48  104M   48 50.2M    0     0  5053k      0  0:00:21  0:00:10  0:00:11 6244k
 54  104M   54 56.6M    0     0  5186k      0  0:00:20  0:00:11  0:00:09 6247k
 59  104M   59 62.5M    0     0  5257k      0  0:00:20  0:00:12  0:00:08 6250k
 65  104M   65 68.9M    0     0  5355k      0  0:00:19  0:00:13  0:00:06 6250k
 71  104M   71 74.7M    0     0  5394k      0  0:00:19  0:00:14  0:00:05 6229k
 77  104M   77 80.6M    0     0  5437k      0  0:00:19  0:00:15  0:00:04 6220k
 83  104M   83 87.0M    0     0  5504k      0  0:00:19  0:00:16  0:00:03 6217k
 88  104M   88 92.8M    0     0  5533k      0  0:00:19  0:00:17  0:00:02 6206k
 94  104M   94 99.2M    0     0  5589k      0  0:00:19  0:00:18  0:00:01 6206k
100  104M  100  104M    0     0  5606k      0  0:00:19  0:00:19 --:--:-- 6218k
==> Validating source files with sha256sums...
    ungoogled-chromium-127.0.6533.119-1-x86_64.pkg.tar.zst ... FAILED
==> ERROR: One or more files did not pass the validity check!
Failed to build ungoogled-chromium-bin
```

**Comment by PF4Public** [comment]
Try redownloading the tarball, I guess

**Comment by networkException** [comment]
I pushed a fix

**Comment by SvenMeyer** [comment]
@networkException Thanks, however after refreshing the database und definitely selecting the -2 version (in pamac GUI), I still get this 
```
Preparing...
Cloning ungoogled-chromium-bin build files...
Generating ungoogled-chromium-bin information...
Checking ungoogled-chromium-bin dependencies...
Resolving dependencies...
Checking inter-conflicts...

Building ungoogled-chromium-bin...
==> Making package: ungoogled-chromium-bin 127.0.6533.119-2 (Tue 20 Aug 2024 03:06:40 UTC)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found ungoogled-chromium-127.0.6533.119-1-x86_64.pkg.tar.zst
==> Validating source files with sha256sums...
    ungoogled-chromium-127.0.6533.119-1-x86_64.pkg.tar.zst ... FAILED
==> ERROR: One or more files did not pass the validity check!
Failed to build ungoogled-chromium-bin
```
